Tests exercises
AleksandrsVerenkovs/c-sharp-syllabus pull request #10
Opened 2021-08-18 11:37 UTC by AleksandrsVerenkovs

Collections_exercise5(WordCount): test negrib pareizi skaitīt vārdus, lai gan uzdevuma parametrus izpilda.

P.S. Polimorfisma testi atvevišķā zarā, jo pie šī zara izveides vēl nebija nodots mājasdarbs.

2021-08-20 17:57 UTC, ausmoons requested changes

2021-08-20 17:57 UTC, ausmoons commented on Arithmetic/Arithmatics.Tests/Exercise1.Tests.cs
> +        public void CompareTest_InputIs15(int x,int y,bool expected)
Testa nosaukums -> Metode_KoPadod_KoSagaida

2021-08-20 17:57 UTC, ausmoons commented on Arithmetic/Arithmatics.Tests/Exercise1.Tests.cs
> +            var actual = Checker.Compare(x, y);
Trūkst // Arrange // Act // Assert komentāru

2021-08-20 17:57 UTC, ausmoons commented on Arithmetic/Exercise_1/Checker.cs
> +            if (num1 == 15 || num2 == 15 || Math.Abs(num1 + num2) == 15) return true;
return uzreiz

2021-08-23 16:42 UTC, ausmoons requested changes

2021-08-23 16:42 UTC, ausmoons commented on Arithmetic/Arithmatics.Tests/Exercise10.Tests.cs
> +        public void Geometry_ProvideRadius_CalculateAreaOfCircle(decimal radius, double expected)
MetodesNosaukums_KoPadod_KoSagaida

2021-08-23 16:42 UTC, ausmoons commented on Arithmetic/Arithmatics.Tests/Exercise10.Tests.cs
>              var actual = CalculateArea.Geometry.areaOfCircle(radius);
CalculateArea.Geometry.areaOfCircle(radius); -- Kāpēc te vēl ir Geometry? AreaOfCircle, nevis area

2021-08-23 16:42 UTC, ausmoons commented on ClassesAndObjects/ClassAndObjectsTests/Exercise12Tests.cs
> +        public void Deposit_ProvideAmount_AddToAccount(decimal initial,decimal money, decimal expected)
Kas ir specifisks šim provided amount? ValidAmout vismaz tad varēja rakstīt. Deposit_ValidAmount_AmountHasBeenAdded

2021-08-23 16:42 UTC, ausmoons commented on Collections/CollectionsTests/Exercise8Tests.cs
> +        public void GetNumber_ProvideName_ReturnErrorMsg()
Kāpēd error message uz name?

2021-08-23 16:42 UTC, ausmoons commented on Collections/CollectionsTests/Exercise8Tests.cs
> +        public void PutNumber_SameNameNewNumber_OverwritesOldNumber()
Šis ir labs nosaukums

2021-08-23 16:42 UTC, ausmoons commented on Collections/CollectionsTests/Exercise8Tests.cs
>              var expected = "4321";
Šis ir pie arrange daļas

2021-08-24 09:02 UTC, AleksandrsVerenkovs commented on Arithmetic/Arithmatics.Tests/Exercise10.Tests.cs
>              var actual = CalculateArea.Geometry.areaOfCircle(radius);
Projekts.Klase.MetodeKlasē(parametrs)

2021-08-24 18:02 UTC, ausmoons approved these changes

2021-08-24 20:50 UTC, merged