Arrays exercises
AleksandrsVerenkovs/c-sharp-syllabus pull request #4
Opened 2021-07-21 13:20 UTC by AleksandrsVerenkovs

Ar 2 vakaru mocībām pie 7. un 8. uzdevumiem.

P.S. Ja 7.uzd tiešām strādā kā vajag, tad tas man sanāca pirmo reizi. 👯

2021-07-21 18:15 UTC, ausmoons requested changes

2021-07-21 18:15 UTC, ausmoons commented on Arrays/Arrays/TicTacToe/Program.cs
> +        private static bool Tie()
Bool Tie un aizpilda laukumu?

2021-07-21 21:46 UTC, AleksandrsVerenkovs commented on Arrays/Arrays/TicTacToe/Program.cs
> +        private static bool Tie()
Kopēju sākuma loģiku no InitBoard.
Tagad ar pēdējo commit pilnībā izdzēsu, ieliku norm 'tie' loģiku.

2021-07-22 18:41 UTC, ausmoons commented on Arrays/Arrays/Exercise2/Program.cs
> +            {
Te nav pareiz tabings in aiz for trūkst atstarpes

2021-07-22 18:46 UTC, ausmoons approved these changes

2021-07-22 19:15 UTC, merged